### ISSUE TITLE
Build broken on Linux (Ubuntu 22.04)

### ISSUE THREAD

**Issue by pacphi** [asaikali/spring-ai-zero-to-hero#2]
I'm using: 

- Maven 3.9.6
- Liberica 21.0.2

**Problem**:

There's a problem w/ `pom.xml` on Linux.  When you attempt to build w/ `mvn clean package`, you get an issue building a child module `image`.  The directory name is actually `Image` (capital `I`). So, on Linux the module name, is case-sensitive.

**Fix**:

Update `pom.xml`:

Change

```
<module>image</module>
```

to

```
<module>Image</module>
```

**Comment by nevenc** [comment]
It's cleaner to have all lowercase :) 
Surprisingly git was not case sensitive, so did an intermediate step and changed back to lowercase.

**Comment by nevenc** [comment]
Fixed.
